import Link from 'next/link'

export const metadata = {
  title: 'Delete Account | AB Data Hub',
  description: 'Learn how to request deletion of your AB Data Hub account and associated personal data.',
}

export default function DeleteAccountPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10">

      {/* Header */}
      <div className="text-center space-y-4 max-w-2xl mx-auto">
        <span className="px-3.5 py-1.5 bg-red-500/10 border border-red-500/20 rounded-full text-xs font-semibold text-red-400 uppercase tracking-wider">
          Account Management
        </span>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          Request Account Deletion
        </h1>
        <p className="text-sm sm:text-base text-silver-muted leading-relaxed">
          This page explains how to permanently delete your <strong className="text-white">AB Data Hub</strong> account and all associated personal data from our systems.
        </p>
      </div>

      {/* Main Content */}
      <div className="bg-dark-bg-secondary/40 border border-silver-muted/10 rounded-2xl glass-dark p-6 sm:p-10 space-y-10 text-sm text-silver-muted leading-relaxed">

        {/* Warning Banner */}
        <div className="flex items-start gap-4 p-4 bg-red-500/8 border border-red-500/20 rounded-xl">
          <svg className="w-6 h-6 text-red-400 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <div>
            <p className="font-bold text-red-400 mb-1">Permanent Action — Cannot Be Undone</p>
            <p className="text-silver-muted text-xs">
              Deleting your account is <strong className="text-white">permanent</strong> and irreversible. Your wallet balance, transaction history, referral earnings, and all personal data will be <strong className="text-white">permanently removed</strong> from our servers.
            </p>
          </div>
        </div>

        {/* What Gets Deleted */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-red-500/15 text-red-400 flex items-center justify-center text-xs">🗑</span>
            Data That Will Be Permanently Deleted
          </h2>
          <ul className="list-disc list-inside space-y-2 pl-2 text-silver-light">
            <li>Your full name, email address, and phone number</li>
            <li>Your account password (encrypted hash) and transaction PIN</li>
            <li>Your wallet balance and all wallet funding records</li>
            <li>All data purchase, airtime, cable TV, electricity, and exam PIN transaction history</li>
            <li>Your referral code, referral earnings, and referral network</li>
            <li>Your profile settings and notification preferences</li>
            <li>Your agent account status and reseller records (if applicable)</li>
          </ul>
        </section>

        {/* What May Be Retained */}
        <section className="space-y-3 pt-6 border-t border-white/5">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-amber-500/15 text-amber-400 flex items-center justify-center text-xs">📋</span>
            Data That May Be Retained
          </h2>
          <p>
            In compliance with Nigerian financial regulations and fraud prevention obligations, the following anonymised records may be retained for up to <strong className="text-white">90 days</strong> after account deletion:
          </p>
          <ul className="list-disc list-inside space-y-2 pl-2 text-silver-light">
            <li>Anonymised transaction reference IDs (for payment dispute resolution)</li>
            <li>Audit log entries generated by administrative actions on your account</li>
          </ul>
          <p className="text-xs text-silver-muted/70 pt-1">
            These records will not contain your name, email, or phone number, and will be permanently purged after the 90-day retention window.
          </p>
        </section>

        {/* How to Delete */}
        <section className="space-y-4 pt-6 border-t border-white/5">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-primary-blue/20 text-primary-glow flex items-center justify-center text-xs">📬</span>
            How to Request Account Deletion
          </h2>
          <p>
            To delete your <strong className="text-white">AB Data Hub</strong> account, follow one of the methods below:
          </p>

          {/* Method 1 */}
          <div className="bg-white/5 border border-white/5 rounded-xl p-5 space-y-2">
            <div className="flex items-center gap-2 font-bold text-white">
              <span className="w-6 h-6 rounded-full bg-primary-blue/30 text-primary-glow flex items-center justify-center text-xs font-extrabold">1</span>
              Via WhatsApp (Fastest — within 24 hours)
            </div>
            <p className="pl-8 text-silver-muted">
              Send a WhatsApp message to our support team with the subject: <strong className="text-white">"Account Deletion Request"</strong>, including your registered email address and phone number.
            </p>
            <div className="pl-8">
              <a
                href="https://wa.me/2347045357195?text=Hello%20AB%20Data%20Hub%20Support%2C%20I%20want%20to%20permanently%20delete%20my%20account%20and%20all%20associated%20data.%20My%20registered%20email%20is%3A%20"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 bg-[#25D366]/10 border border-[#25D366]/20 text-[#25D366] font-semibold rounded-xl text-xs hover:bg-[#25D366]/20 transition-all"
              >
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.514 2.266 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.734-1.45L0 24zm6.59-4.846c1.6.95 3.188 1.449 4.825 1.451 5.436 0 9.86-4.42 9.864-9.864.002-2.637-1.03-5.116-2.905-6.994C16.557 1.866 14.077.835 11.44.835c-5.448 0-9.88 4.417-9.884 9.864-.002 2.01.52 3.975 1.517 5.688l-1.015 3.701 3.792-.995z" />
                </svg>
                Send WhatsApp Request — 07045357195
              </a>
            </div>
          </div>

          {/* Method 2 */}
          <div className="bg-white/5 border border-white/5 rounded-xl p-5 space-y-2">
            <div className="flex items-center gap-2 font-bold text-white">
              <span className="w-6 h-6 rounded-full bg-primary-blue/30 text-primary-glow flex items-center justify-center text-xs font-extrabold">2</span>
              Via Phone Call
            </div>
            <p className="pl-8 text-silver-muted">
              Call our support line directly and request account deletion. Our team will verify your identity and process the request within <strong className="text-white">24–48 hours</strong>.
            </p>
            <div className="pl-8">
              <a
                href="tel:08133887526"
                className="inline-flex items-center gap-2 px-4 py-2 bg-primary-blue/10 border border-primary-blue/20 text-primary-glow font-semibold rounded-xl text-xs hover:bg-primary-blue/20 transition-all"
              >
                📞 Call: 08133887526
              </a>
            </div>
          </div>

          {/* Response Timeline */}
          <div className="p-4 bg-emerald-500/5 border border-emerald-500/15 rounded-xl text-xs text-silver-light">
            <p className="font-semibold text-emerald-400 mb-1">⏱ Processing Timeline</p>
            <p>Account deletion requests are typically processed within <strong className="text-white">24–48 hours</strong> of verification. You will receive a confirmation message once your account and all associated data have been fully deleted.</p>
          </div>
        </section>

      </div>

      {/* Back Link */}
      <div className="flex justify-center gap-4 pt-2">
        <Link
          href="/"
          className="px-5 py-2.5 border border-silver-muted/15 hover:bg-white/5 text-silver-light font-semibold rounded-xl text-sm transition-all"
        >
          ← Back to Homepage
        </Link>
        <Link
          href="/privacy"
          className="px-5 py-2.5 bg-gradient-blue hover:opacity-95 text-white font-bold rounded-xl shadow-glow-blue transition-all text-sm"
        >
          View Privacy Policy
        </Link>
      </div>
    </div>
  )
}
